# DATA 606 FINAL PROJECT
## WEBSCRAPING THE WEBSITE 'TRUECAR.COM' FOR GETTING THE DATA OF USED CARS
### Importing required packages for scraping

In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import lxml.html as lxl
import numpy as np

### Accessing the truecar.com website and fetching the details of cars using Beautiful Soup and finding the attributes of the datasets

In [3]:
%%time
make=[]
model=[]
trim=[]
year = []
mileage = []
location = []
engine=[]
transmission=[]
drive_type=[]
price = []
exterior_color=[]
interior_color=[]
vehicle_history=[]
MPG_city=[]
MPG_highway=[]
VIN=[]
accidents =[]
owners=[]
car_usage_type=[]
fuel_type=[]


filename = 'Used Cars Prices_TRUECAR'

for i in range (1,2000):
    
    
    base_url = 'https://www.truecar.com/used-cars-for-sale/listings/'
    
    url = base_url + '?page=' + str(i)
    
    
    req = requests.get(url)

    soup = BeautifulSoup(req.text,'html.parser')

    output_details=soup.find_all('div', {'class': 'vehicle-card'})
    
    
    
    for output in output_details:
    
 
        current_car = output.find('span',{'class':"vehicle-header-make-model text-truncate"}).get_text()
    
        try:
            make.append(current_car.split(' ')[0])
        except:
            make.append('n/a')
    
        try:
            model.append(current_car.split(' ')[1])
        except:
            model.append('n/a')
    
        try:
            trim.append(output.find('div',{'class':"font-size-1 text-truncate"}).get_text())
        
        except:
            trim.append('n/a')
    
        try:
            year.append(output.find('span',{'class':"vehicle-card-year font-size-1"}).get_text())
        except:
            year.append('n/a')
        
          
        

        try:
            cur_mlg=output.find('div',{'data-test':"vehicleMileage"}).get_text()
            mileage.append(cur_mlg.split(' ')[0])
        except:
            mileage.append('n/a')
    
        
        try:
            location.append(output.find('div',{'data-test':"vehicleCardLocation"}).get_text())
        except:
            location.append('n/a')    
        
    

        try:
            pr=output.find('div',{'data-test':"vehicleListingPriceAmount"}).get_text()
            price.append(pr.split('$')[1])
        except:
            price.append('n/a')
        
        
        clr=output.find('div',{'class':"vehicle-card-location font-size-1 margin-top-1 text-truncate"}).get_text()
    
        try:
            exterior_color.append(clr.split(',')[0].split(' ')[0])
        except:
            exterior_color.append('n/a')
    
        try:
            interior_color.append(clr.split(',')[1].split(' ')[1])
        except:
            interior_color.append('n/a')
        
        vhkl_hist=output.find('div',{'data-test':"vehicleCardCondition"}).get_text()
    
        try:
            acc=vhkl_hist.split(',')[0].split(' ')[0]
            if acc == 'No':
                accidents.append('0')
            else:
                accidents.append(acc)
        except:
            accidents.append('n/a')
        
        try:
            owners.append(vhkl_hist.split(',')[1].split(' ')[1])
        except:
            owners.append('n/a')
        
        try:
            car_usage_type.append(vhkl_hist.split(',')[2])
        except:
            car_usage_type.append('n/a')
        
        
        met = output.find('div',{'class':"font-size-1 margin-top-1"}).get_text()
    
        try:
            MPG_city.append(((met.split(',')[0]).split(':')[1]).split('-')[0])
        except:
            MPG_city.append('n/a')
        
        try:
            MPG_highway.append(((met.split(',')[0]).split(':')[1]).split('-')[1])
        except:
            MPG_highway.append('n/a')
        
        try:
            engine.append(((met.split(',')[1].split(':')[1]).split(' ')[1]).split('L')[0])
        except:
            engine.append('n/a')
        
        try:
            transmission.append((met.split(',')[2]).split(':')[1])
        except:
            transmission.append('n/a')
            
        try:
            drive_type.append((met.split(',')[-1]))
        except:
            drive_type.append('n/a')
            
        try:
            ft=((met.split(',')[1]).split(':')[1]).split(' ')
            if ft[-1]=='Turbocharged' or ft[-1]=='Twin-Turbo':
                fuel_type.append(ft[-2])
            else: 
                fuel_type.append(ft[-1])
        except:
            fuel_type.append('n/a')
        
        try:
            VIN.append((output.find('div',{'class':"font-size-1 vehicle-card-vin-challenger"}).get_text()).split(':')[1])
        except:
            VIN.append('n/a')

CPU times: user 8min 10s, sys: 4.49 s, total: 8min 14s
Wall time: 58min 49s

### Preparing columns for the Dataset

In [4]:
Used_Cars = pd.DataFrame({'VIN':VIN,'Brand': make, 'Model': model, 'Trim' : trim, 'Manufature_Year': year,
                          'Mileage':mileage,'MPG_City': MPG_city,'MPG_Highway':MPG_highway,'Engine_Capacity':engine, 
                          'Transmission': transmission,'Drive_Type' : drive_type, 'Fuel_Type': fuel_type,
                          'Exterior_Color' : exterior_color, 'Interior_Color' : interior_color,'Accidents':accidents,
                          'Owners':owners,'Car_Usage_Type':car_usage_type, 'Location':location,'Price': price})

### Displaying the dataset

In [5]:
Used_Cars.index=Used_Cars.VIN
del Used_Cars['VIN']
Used_Cars

,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
VIN,,,,,,,,,,,,,,,,,,
5UXJU2C50KLN66994,BMW,X5,xDrive50i,2019,"28,727",17,22,4.4,Automatic,AWD,Gas,Blue,White,0,1,Personal use,"West Palm Beach, FL","59,498"
2T1BURHE4GC512250,Toyota,Corolla,LE CVT,2016,"107,628",29,38,1.8,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"East Greenwich, RI","15,499"
WP1AA2A52MLB14348,Porsche,Macan,AWD,2021,"1,018",19,23,2.0,Automatic,AWD,Gas,Black,Black,0,1,Personal use,"North Lauderdale, FL","61,999"
1G1ZD5ST8LF011564,Chevrolet,Malibu,LT,2020,"73,364",29,36,1.5,Automatic,FWD,Gas,Silver,Black,0,2,Personal use,"Sebring, FL","19,998"
1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2FMPK3J91JBB86053,Ford,Edge,SEL FWD,2018,"51,357",20,29,2.0,Automatic,FWD,Gas,Silver,Black,0,1,Personal use,"Decatur, TX","24,577"
JTHFN48Y840051943,Lexus,SC,SC 430 Convertible,2004,"61,414",18,23,4.3,Automatic,RWD,Gas,Black,Black,0,4,Personal use,"Sarasota, FL","19,990"
KM8J3CAL5KU866807,Hyundai,Tucson,Ultimate AWD,2019,"32,594",21,26,2.4,Automatic,AWD,Gas,Black,Black,1,1,Personal use,"Bradenton, FL","26,495"
2GCEC19T541208434,Chevrolet,Silverado,WT Extended Cab Standard Box 2WD,2004,"200,000",15,20,5.3,Automatic,RWD,Gas,Silver,Black,1,6,Personal use,"Cedar Falls, IA","4,500"
1C4HJWDGXJL828664,Jeep,Wrangler,Unlimited Sport S (JK),2018,"32,070",n/a,n/a,n/a,n/a,Certified Pre-Owned,n/a,Gray,Black,0,1,Fleet use,"Newark, CA","32,704"

### Converting the dataframe to a csv file for easy access and handling

In [6]:
Used_Cars.to_csv("{}.csv".format(filename))
df = pd.read_csv('Used Cars Prices_TRUECAR.csv', index_col=0)
df

/Users/saidababugarlapati/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
VIN,,,,,,,,,,,,,,,,,,
5UXJU2C50KLN66994,BMW,X5,xDrive50i,2019,"28,727",17,22,4.4,Automatic,AWD,Gas,Blue,White,0,1,Personal use,"West Palm Beach, FL","59,498"
2T1BURHE4GC512250,Toyota,Corolla,LE CVT,2016,"107,628",29,38,1.8,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"East Greenwich, RI","15,499"
WP1AA2A52MLB14348,Porsche,Macan,AWD,2021,"1,018",19,23,2.0,Automatic,AWD,Gas,Black,Black,0,1,Personal use,"North Lauderdale, FL","61,999"
1G1ZD5ST8LF011564,Chevrolet,Malibu,LT,2020,"73,364",29,36,1.5,Automatic,FWD,Gas,Silver,Black,0,2,Personal use,"Sebring, FL","19,998"
1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2FMPK3J91JBB86053,Ford,Edge,SEL FWD,2018,"51,357",20,29,2.0,Automatic,FWD,Gas,Silver,Black,0,1,Personal use,"Decatur, TX","24,577"
JTHFN48Y840051943,Lexus,SC,SC 430 Convertible,2004,"61,414",18,23,4.3,Automatic,RWD,Gas,Black,Black,0,4,Personal use,"Sarasota, FL","19,990"
KM8J3CAL5KU866807,Hyundai,Tucson,Ultimate AWD,2019,"32,594",21,26,2.4,Automatic,AWD,Gas,Black,Black,1,1,Personal use,"Bradenton, FL","26,495"
2GCEC19T541208434,Chevrolet,Silverado,WT Extended Cab Standard Box 2WD,2004,"200,000",15,20,5.3,Automatic,RWD,Gas,Silver,Black,1,6,Personal use,"Cedar Falls, IA","4,500"
1C4HJWDGXJL828664,Jeep,Wrangler,Unlimited Sport S (JK),2018,"32,070",NaN,NaN,NaN,NaN,Certified Pre-Owned,NaN,Gray,Black,0,1,Fleet use,"Newark, CA","32,704"

### Final Dataset after dropping the null values

In [7]:
df=df.dropna()
df=df.reset_index()
df

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
0,5UXJU2C50KLN66994,BMW,X5,xDrive50i,2019,"28,727",17,22,4.4,Automatic,AWD,Gas,Blue,White,0,1,Personal use,"West Palm Beach, FL","59,498"
1,2T1BURHE4GC512250,Toyota,Corolla,LE CVT,2016,"107,628",29,38,1.8,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"East Greenwich, RI","15,499"
2,WP1AA2A52MLB14348,Porsche,Macan,AWD,2021,"1,018",19,23,2.0,Automatic,AWD,Gas,Black,Black,0,1,Personal use,"North Lauderdale, FL","61,999"
3,1G1ZD5ST8LF011564,Chevrolet,Malibu,LT,2020,"73,364",29,36,1.5,Automatic,FWD,Gas,Silver,Black,0,2,Personal use,"Sebring, FL","19,998"
4,1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51030,3GCUYEEDXLG110637,Chevrolet,Silverado,RST Crew Cab Short Bed 4WD,2020,"54,064",19,22,5.3,Automatic,4WD,Gas,Black,Black,1,1,Personal use,"Birmingham, AL","45,000"
51031,2FMPK3J91JBB86053,Ford,Edge,SEL FWD,2018,"51,357",20,29,2.0,Automatic,FWD,Gas,Silver,Black,0,1,Personal use,"Decatur, TX","24,577"
51032,JTHFN48Y840051943,Lexus,SC,SC 430 Convertible,2004,"61,414",18,23,4.3,Automatic,RWD,Gas,Black,Black,0,4,Personal use,"Sarasota, FL","19,990"
51033,KM8J3CAL5KU866807,Hyundai,Tucson,Ultimate AWD,2019,"32,594",21,26,2.4,Automatic,AWD,Gas,Black,Black,1,1,Personal use,"Bradenton, FL","26,495"
51034,2GCEC19T541208434,Chevrolet,Silverado,WT Extended Cab Standard Box 2WD,2004,"200,000",15,20,5.3,Automatic,RWD,Gas,Silver,Black,1,6,Personal use,"Cedar Falls, IA","4,500"

### Creating a csv file for final dataset

In [8]:
fn='TrueCar Used Cars Dataset'
df.to_csv("{}.csv".format(fn))
df1 = pd.read_csv('TrueCar Used Cars Dataset.csv', index_col=0)
df1

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
0,5UXJU2C50KLN66994,BMW,X5,xDrive50i,2019,"28,727",17,22,4.4,Automatic,AWD,Gas,Blue,White,0,1,Personal use,"West Palm Beach, FL","59,498"
1,2T1BURHE4GC512250,Toyota,Corolla,LE CVT,2016,"107,628",29,38,1.8,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"East Greenwich, RI","15,499"
2,WP1AA2A52MLB14348,Porsche,Macan,AWD,2021,"1,018",19,23,2.0,Automatic,AWD,Gas,Black,Black,0,1,Personal use,"North Lauderdale, FL","61,999"
3,1G1ZD5ST8LF011564,Chevrolet,Malibu,LT,2020,"73,364",29,36,1.5,Automatic,FWD,Gas,Silver,Black,0,2,Personal use,"Sebring, FL","19,998"
4,1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51030,3GCUYEEDXLG110637,Chevrolet,Silverado,RST Crew Cab Short Bed 4WD,2020,"54,064",19,22,5.3,Automatic,4WD,Gas,Black,Black,1,1,Personal use,"Birmingham, AL","45,000"
51031,2FMPK3J91JBB86053,Ford,Edge,SEL FWD,2018,"51,357",20,29,2.0,Automatic,FWD,Gas,Silver,Black,0,1,Personal use,"Decatur, TX","24,577"
51032,JTHFN48Y840051943,Lexus,SC,SC 430 Convertible,2004,"61,414",18,23,4.3,Automatic,RWD,Gas,Black,Black,0,4,Personal use,"Sarasota, FL","19,990"
51033,KM8J3CAL5KU866807,Hyundai,Tucson,Ultimate AWD,2019,"32,594",21,26,2.4,Automatic,AWD,Gas,Black,Black,1,1,Personal use,"Bradenton, FL","26,495"
51034,2GCEC19T541208434,Chevrolet,Silverado,WT Extended Cab Standard Box 2WD,2004,"200,000",15,20,5.3,Automatic,RWD,Gas,Silver,Black,1,6,Personal use,"Cedar Falls, IA","4,500"

In [9]:
file = 'TrueCar Used Cars Dataset View'
df2=df1[:201]
df2.to_csv("{}.csv".format(file))
view_dataset = pd.read_csv('TrueCar Used Cars Dataset View.csv',index_col=0)
view_dataset

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
0,5UXJU2C50KLN66994,BMW,X5,xDrive50i,2019,"28,727",17,22,4.4,Automatic,AWD,Gas,Blue,White,0,1,Personal use,"West Palm Beach, FL","59,498"
1,2T1BURHE4GC512250,Toyota,Corolla,LE CVT,2016,"107,628",29,38,1.8,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"East Greenwich, RI","15,499"
2,WP1AA2A52MLB14348,Porsche,Macan,AWD,2021,"1,018",19,23,2.0,Automatic,AWD,Gas,Black,Black,0,1,Personal use,"North Lauderdale, FL","61,999"
3,1G1ZD5ST8LF011564,Chevrolet,Malibu,LT,2020,"73,364",29,36,1.5,Automatic,FWD,Gas,Silver,Black,0,2,Personal use,"Sebring, FL","19,998"
4,1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,1FADP3E28HL214260,Ford,Focus,S Sedan,2017,"96,080",25,34,2.0,Automatic,FWD,Gas,Black,Black,0,1,Personal use,"Midlothian, TX","9,888"
197,5NPE24AF8GH387615,Hyundai,Sonata,SE 2.4L,2016,"91,890",25,38,2.4,Automatic,FWD,Gas,White,Gray,0,3,Personal use,"Colma, CA","13,992"
198,1FM5K8D81KGA97049,Ford,Explorer,XLT 4WD,2019,"74,900",16,22,3.5,Automatic,4WD,Gas,Gray,Black,0,1,Fleet use,"Garfield, NJ","24,895"
199,JTDEPRAE7LJ035312,Toyota,Corolla,LE CVT,2020,"4,721",30,38,1.8,Automatic,FWD,Gas,Silver,Black,0,2,Personal use,"Arlington, TX","22,642"
200,1C4RJEAG3LC245973,Jeep,Grand,Altitude RWD,2020,"81,873",19,26,3.6,Automatic,RWD,Gas,Black,Black,0,2,Personal use,"Maitland, FL","24,989"

In [10]:
display(df1.sort_values(by='Price',ascending=False).head(10))
df.sort_values(by='Price',ascending=True).head(10)

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
7193,ZFFAA54A550139986,Ferrari,612,Coupe,2005,"15,104",11,17,5.8,Automatic,RWD,Gas,Black,Brown,0,2,Personal use,"New York, NY","99,995"
1470,SALGW3FE6HA347803,Land,Rover,V8 Supercharged SV Autobiography LWB,2017,"47,635",14,19,5.0,Automatic,4WD,Supercharged,Gray,Black,0,2,Personal use,"Sarasota, FL","98,981"
134,SALGS2SE9LA593314,Land,Rover,HSE P525 V8 Supercharged SWB,2020,"32,313",16,21,5.0,Automatic,4WD,Supercharged,White,Unknown,0,1,Personal use,"Maitland, FL","97,988"
8560,1C6SRFU90MN776770,Ram,1500,"TRX Crew Cab 5'7"" Box 4WD",2021,"6,107",10,14,6.2,Automatic,4WD,Supercharged,White,Black,0,1,Personal use,"St. Petersburg, FL","93,998"
39657,3FA6P0H75DR108987,Ford,Fusion,SE FWD,2013,"127,772",22,34,2.5,Automatic,FWD,Gas,Black,Beige,0,1,Personal use,"Rio Linda, CA","9,999"
32608,3FA6P0H75DR108987,Ford,Fusion,SE FWD,2013,"127,772",22,34,2.5,Automatic,FWD,Gas,Black,Beige,0,1,Personal use,"Rio Linda, CA","9,999"
32659,3FA6P0H75DR108987,Ford,Fusion,SE FWD,2013,"127,772",22,34,2.5,Automatic,FWD,Gas,Black,Beige,0,1,Personal use,"Rio Linda, CA","9,999"
10377,3FA6P0H75DR108987,Ford,Fusion,SE FWD,2013,"127,772",22,34,2.5,Automatic,FWD,Gas,Black,Beige,0,1,Personal use,"Rio Linda, CA","9,999"
23352,3FA6P0H75DR108987,Ford,Fusion,SE FWD,2013,"127,772",22,34,2.5,Automatic,FWD,Gas,Black,Beige,0,1,Personal use,"Rio Linda, CA","9,999"
37399,3FA6P0H75DR108987,Ford,Fusion,SE FWD,2013,"127,772",22,34,2.5,Automatic,FWD,Gas,Black,Beige,0,1,Personal use,"Rio Linda, CA","9,999"

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
8574,1G1NE52J6Y6217080,Chevrolet,Malibu,LS,2000,"198,207",22,30,3.1,Automatic,FWD,Gas,Silver,Unknown,1,7,Personal use,"Seattle, WA","1,991"
2193,JN8AS5MT3DW035347,Nissan,Rogue,S FWD,2013,"101,972",23,28,2.5,Automatic,FWD,Gas,Gray,Gray,3,4,Fleet use,"Ocala, FL","10,000"
1534,3N1AB7AP6FL629506,Nissan,Sentra,SV CVT,2015,"126,142",29,39,1.8,Automatic,FWD,Gas,White,Black,1,2,Personal use,"Las Vegas, NV","10,000"
2195,JN8AS5MT3DW035347,Nissan,Rogue,S FWD,2013,"101,972",23,28,2.5,Automatic,FWD,Gas,Gray,Gray,3,4,Fleet use,"Ocala, FL","10,000"
8468,5NPE24AF0FH142810,Hyundai,Sonata,SE 2.4L,2015,"136,262",25,37,2.4,Automatic,FWD,Gas,Gray,Gray,2,2,Personal use,"Bellevue, NE","10,000"
7879,2HGFB2F53FH544579,Honda,Civic,LX Sedan CVT,2015,"160,825",30,39,1.8,Automatic,FWD,Gas,Silver,Gray,1,2,Personal use,"Paramus, NJ","10,000"
1968,2C4RC1BG5ER125152,Chrysler,Town,Touring,2014,"109,016",17,25,3.6,Automatic,FWD,Gas,Blue,Beige,1,3,Personal use,"Jacksonville, FL","10,000"
3574,JN8AS5MT6FW652034,Nissan,Rogue,S FWD,2015,"133,437",23,28,2.5,Automatic,FWD,Gas,White,Gray,0,2,Personal use,"Houston, TX","10,000"
7567,5GTDN13E478114605,HUMMER,H3,SUV,2007,"134,771",14,18,3.7,Automatic,4WD,Gas,Unknown,Gray,0,6,Personal use,"Phoenix, AZ","10,000"
5323,1C6RD6FT8CS333210,Ram,1500,"Express Quad Cab 6'4"" Box 2WD",2012,"169,698",14,20,5.7,Automatic,RWD,Gas,White,Gray,0,2,Personal use,"Snyder, TX","10,000"