# DATA 606 FINAL PROJECT
## WEBSCRAPING THE WEBSITE 'TRUECAR.COM' FOR GETTING THE DATA OF USED CARS
### Importing required packages for scraping

In [9]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import lxml.html as lxl
import numpy as np

### Accessing the truecar.com website and fetching the details of cars using Beautiful Soup

In [10]:
base_url = 'https://www.truecar.com/used-cars-for-sale/listings/'

req = requests.get(base_url)

soup = BeautifulSoup(req.text,'html.parser')

output_details=soup.find_all('div', {'class': 'vehicle-card'})

### Finding the attributes of the datasets

In [11]:

make=[]
model=[]
trim=[]
year = []
mileage = []
location = []
engine=[]
transmission=[]
drive_type=[]
price = []
exterior_color=[]
interior_color=[]
vehicle_history=[]
MPG_city=[]
MPG_highway=[]
VIN=[]
accidents =[]
owners=[]
car_usage_type=[]
fuel_type=[]

filename = 'Used Cars Prices_TRUECAR'

for i in range (1,2600):
    
    
    for output in output_details:
    
 
        current_car = output.find('span',{'class':"vehicle-header-make-model text-truncate"}).get_text()
    
        try:
            make.append(current_car.split(' ')[0])
        except:
            make.append('n/a')
    
        try:
            model.append(current_car.split(' ')[1])
        except:
            model.append('n/a')
    
        try:
            trim.append(output.find('div',{'class':"font-size-1 text-truncate"}).get_text())
        
        except:
            trim.append('n/a')
    
        try:
            year.append(output.find('span',{'class':"vehicle-card-year font-size-1"}).get_text())
        except:
            year.append('n/a')
        
          
        

        try:
            cur_mlg=output.find('div',{'data-test':"vehicleMileage"}).get_text()
            mileage.append(cur_mlg.split(' ')[0])
        except:
            mileage.append('n/a')
    
        
        try:
            location.append(output.find('div',{'data-test':"vehicleCardLocation"}).get_text())
        except:
            location.append('n/a')    
        
    

        try:
            pr=output.find('div',{'data-test':"vehicleListingPriceAmount"}).get_text()
            price.append(pr.split('$')[1])
        except:
            price.append('n/a')
        
        
        clr=output.find('div',{'class':"vehicle-card-location font-size-1 margin-top-1 text-truncate"}).get_text()
    
        try:
            exterior_color.append(clr.split(',')[0].split(' ')[0])
        except:
            exterior_color.append('n/a')
    
        try:
            interior_color.append(clr.split(',')[1].split(' ')[1])
        except:
            interior_color.append('n/a')
        
        vhkl_hist=output.find('div',{'data-test':"vehicleCardCondition"}).get_text()
    
        try:
            acc=vhkl_hist.split(',')[0].split(' ')[0]
            if acc == 'No':
                accidents.append('0')
            else:
                accidents.append(acc)
        except:
            accidents.append('n/a')
        
        try:
            owners.append(vhkl_hist.split(',')[1].split(' ')[1])
        except:
            owners.append('n/a')
        
        try:
            car_usage_type.append(vhkl_hist.split(',')[2])
        except:
            car_usage_type.append('n/a')
        
        
        met = output.find('div',{'class':"font-size-1 margin-top-1"}).get_text()
    
        try:
            MPG_city.append(((met.split(',')[0]).split(':')[1]).split('-')[0])
        except:
            MPG_city.append('n/a')
        
        try:
            MPG_highway.append(((met.split(',')[0]).split(':')[1]).split('-')[1])
        except:
            MPG_highway.append('n/a')
        
        try:
            engine.append(((met.split(',')[1].split(':')[1]).split(' ')[1]).split('L')[0])
        except:
            engine.append('n/a')
        
        try:
            transmission.append((met.split(',')[2]).split(':')[1])
        except:
            transmission.append('n/a')
            
        try:
            drive_type.append((met.split(',')[-1]))
        except:
            drive_type.append('n/a')
            
        try:
            ft=((met.split(',')[1]).split(':')[1]).split(' ')
            if ft[-1]=='Turbocharged' or ft[-1]=='Twin-Turbo':
                fuel_type.append(ft[-2])
            else: 
                fuel_type.append(ft[-1])
        except:
            fuel_type.append('n/a')
        
        try:
            VIN.append((output.find('div',{'class':"font-size-1 vehicle-card-vin-challenger"}).get_text()).split(':')[1])
        except:
            VIN.append('n/a')

### Preparing columns for the Dataset

In [12]:
Used_Cars = pd.DataFrame({'VIN':VIN,'Brand': make, 'Model': model, 'Trim' : trim, 'Manufature_Year': year,
                          'Mileage':mileage,'MPG_City': MPG_city,'MPG_Highway':MPG_highway,'Engine_Capacity':engine, 
                          'Transmission': transmission,'Drive_Type' : drive_type, 'Fuel_Type': fuel_type,
                          'Exterior_Color' : exterior_color, 'Interior_Color' : interior_color,'Accidents':accidents,
                          'Owners':owners,'Car_Usage_Type':car_usage_type, 'Location':location,'Price': price})

### Displaying the dataset

In [13]:
Used_Cars.index=Used_Cars.VIN
del Used_Cars['VIN']
Used_Cars

,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
VIN,,,,,,,,,,,,,,,,,,
5TDYK3DC2FS683067,Toyota,Sienna,XLE 8-Passenger FWD,2015,"51,825",18,25,3.5,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"Clayton, ID","27,999"
5XYPG4A31KG450330,Kia,Sorento,LX I4 FWD,2019,"68,125",22,29,2.4,Automatic,FWD,Gas,Gray,Black,1,2,Fleet use,"Santa Ana, CA","22,779"
1GNSKCKJ2KR159005,Chevrolet,Tahoe,Premier 4WD,2019,"28,170",15,21,6.2,Automatic,4WD,Gas,White,Black,0,1,Personal use,"Pelham, AL","61,990"
1FMCU0GD4JUA78698,Ford,Escape,SE FWD,2018,"138,293",23,30,1.5,Automatic,FWD,Gas,White,Gray,0,1,Personal use,"Melbourne, FL","12,998"
1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1FTFW1E56JFB74611,Ford,F-150,Lariat SuperCrew 5.5' Box 4WD,2018,"129,900",19,24,5.0,Automatic,4WD,Gas,White,Unknown,0,2,Personal use,"Blackfoot, ID","28,999"
JTDKN3DU0A0180414,Toyota,Prius,Two,2010,"111,131",48,51,1.8,Automatic,FWD,Hybrid,Silver,Gray,0,2,Personal use,"Newport Beach, CA","9,937"
1FT7W2B63LEC22226,Ford,Super,XLT Crew Cab 6.75' Box 4WD,2020,"78,819",6.2L V,8 Gas,Automatic,n/a,4WD,Automatic,Black,Gray,1,1,Personal use,"McAllen, TX","48,995"
1G1ZD5ST5LF031433,Chevrolet,Malibu,LT,2020,"59,236",29,36,1.5,Automatic,FWD,Gas,Black,Black,0,1,Personal use,"Metairie, LA","21,200"
1FTEW1E8XGFB48012,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2016,"138,684",17,23,3.5,Automatic,4WD,Gas,Blue,Gray,0,1,Personal use,"Grand Rapids, MI","20,990"

### Converting the dataframe to a csv file for easy access and handling

In [14]:
Used_Cars.to_csv("{}.csv".format(filename))
df = pd.read_csv('Used Cars Prices_TRUECAR.csv', index_col=0)
df

,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
VIN,,,,,,,,,,,,,,,,,,
5TDYK3DC2FS683067,Toyota,Sienna,XLE 8-Passenger FWD,2015,"51,825",18,25,3.5,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"Clayton, ID","27,999"
5XYPG4A31KG450330,Kia,Sorento,LX I4 FWD,2019,"68,125",22,29,2.4,Automatic,FWD,Gas,Gray,Black,1,2,Fleet use,"Santa Ana, CA","22,779"
1GNSKCKJ2KR159005,Chevrolet,Tahoe,Premier 4WD,2019,"28,170",15,21,6.2,Automatic,4WD,Gas,White,Black,0,1,Personal use,"Pelham, AL","61,990"
1FMCU0GD4JUA78698,Ford,Escape,SE FWD,2018,"138,293",23,30,1.5,Automatic,FWD,Gas,White,Gray,0,1,Personal use,"Melbourne, FL","12,998"
1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1FTFW1E56JFB74611,Ford,F-150,Lariat SuperCrew 5.5' Box 4WD,2018,"129,900",19,24,5.0,Automatic,4WD,Gas,White,Unknown,0,2,Personal use,"Blackfoot, ID","28,999"
JTDKN3DU0A0180414,Toyota,Prius,Two,2010,"111,131",48,51,1.8,Automatic,FWD,Hybrid,Silver,Gray,0,2,Personal use,"Newport Beach, CA","9,937"
1FT7W2B63LEC22226,Ford,Super,XLT Crew Cab 6.75' Box 4WD,2020,"78,819",6.2L V,8 Gas,Automatic,NaN,4WD,Automatic,Black,Gray,1,1,Personal use,"McAllen, TX","48,995"
1G1ZD5ST5LF031433,Chevrolet,Malibu,LT,2020,"59,236",29,36,1.5,Automatic,FWD,Gas,Black,Black,0,1,Personal use,"Metairie, LA","21,200"
1FTEW1E8XGFB48012,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2016,"138,684",17,23,3.5,Automatic,4WD,Gas,Blue,Gray,0,1,Personal use,"Grand Rapids, MI","20,990"

### Final Dataset after dropping the null values

In [15]:
df=df.dropna()
df=df.reset_index()
df

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
0,5TDYK3DC2FS683067,Toyota,Sienna,XLE 8-Passenger FWD,2015,"51,825",18,25,3.5,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"Clayton, ID","27,999"
1,5XYPG4A31KG450330,Kia,Sorento,LX I4 FWD,2019,"68,125",22,29,2.4,Automatic,FWD,Gas,Gray,Black,1,2,Fleet use,"Santa Ana, CA","22,779"
2,1GNSKCKJ2KR159005,Chevrolet,Tahoe,Premier 4WD,2019,"28,170",15,21,6.2,Automatic,4WD,Gas,White,Black,0,1,Personal use,"Pelham, AL","61,990"
3,1FMCU0GD4JUA78698,Ford,Escape,SE FWD,2018,"138,293",23,30,1.5,Automatic,FWD,Gas,White,Gray,0,1,Personal use,"Melbourne, FL","12,998"
4,1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77965,1GNEVGKW3KJ219606,Chevrolet,Traverse,LT Cloth with 1LT AWD,2019,"129,787",17,25,3.6,Automatic,AWD,Gas,Black,Black,1,1,Personal use,"Lima, OH","21,975"
77966,1FTFW1E56JFB74611,Ford,F-150,Lariat SuperCrew 5.5' Box 4WD,2018,"129,900",19,24,5.0,Automatic,4WD,Gas,White,Unknown,0,2,Personal use,"Blackfoot, ID","28,999"
77967,JTDKN3DU0A0180414,Toyota,Prius,Two,2010,"111,131",48,51,1.8,Automatic,FWD,Hybrid,Silver,Gray,0,2,Personal use,"Newport Beach, CA","9,937"
77968,1G1ZD5ST5LF031433,Chevrolet,Malibu,LT,2020,"59,236",29,36,1.5,Automatic,FWD,Gas,Black,Black,0,1,Personal use,"Metairie, LA","21,200"
77969,1FTEW1E8XGFB48012,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2016,"138,684",17,23,3.5,Automatic,4WD,Gas,Blue,Gray,0,1,Personal use,"Grand Rapids, MI","20,990"

### Creating a csv file for final dataset

In [16]:
fn='TrueCar Used Cars Dataset'
df.to_csv("{}.csv".format(fn))
df1 = pd.read_csv('TrueCar Used Cars Dataset.csv', index_col=0)
df1

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
0,5TDYK3DC2FS683067,Toyota,Sienna,XLE 8-Passenger FWD,2015,"51,825",18,25,3.5,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"Clayton, ID","27,999"
1,5XYPG4A31KG450330,Kia,Sorento,LX I4 FWD,2019,"68,125",22,29,2.4,Automatic,FWD,Gas,Gray,Black,1,2,Fleet use,"Santa Ana, CA","22,779"
2,1GNSKCKJ2KR159005,Chevrolet,Tahoe,Premier 4WD,2019,"28,170",15,21,6.2,Automatic,4WD,Gas,White,Black,0,1,Personal use,"Pelham, AL","61,990"
3,1FMCU0GD4JUA78698,Ford,Escape,SE FWD,2018,"138,293",23,30,1.5,Automatic,FWD,Gas,White,Gray,0,1,Personal use,"Melbourne, FL","12,998"
4,1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77965,1GNEVGKW3KJ219606,Chevrolet,Traverse,LT Cloth with 1LT AWD,2019,"129,787",17,25,3.6,Automatic,AWD,Gas,Black,Black,1,1,Personal use,"Lima, OH","21,975"
77966,1FTFW1E56JFB74611,Ford,F-150,Lariat SuperCrew 5.5' Box 4WD,2018,"129,900",19,24,5.0,Automatic,4WD,Gas,White,Unknown,0,2,Personal use,"Blackfoot, ID","28,999"
77967,JTDKN3DU0A0180414,Toyota,Prius,Two,2010,"111,131",48,51,1.8,Automatic,FWD,Hybrid,Silver,Gray,0,2,Personal use,"Newport Beach, CA","9,937"
77968,1G1ZD5ST5LF031433,Chevrolet,Malibu,LT,2020,"59,236",29,36,1.5,Automatic,FWD,Gas,Black,Black,0,1,Personal use,"Metairie, LA","21,200"
77969,1FTEW1E8XGFB48012,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2016,"138,684",17,23,3.5,Automatic,4WD,Gas,Blue,Gray,0,1,Personal use,"Grand Rapids, MI","20,990"

In [17]:
file = 'TrueCar Used Cars Dataset View'
df2=df1[:201]
df2.to_csv("{}.csv".format(file))
view_dataset = pd.read_csv('TrueCar Used Cars Dataset View.csv',index_col=0)
view_dataset

,VIN,Brand,Model,Trim,Manufature_Year,Mileage,MPG_City,MPG_Highway,Engine_Capacity,Transmission,Drive_Type,Fuel_Type,Exterior_Color,Interior_Color,Accidents,Owners,Car_Usage_Type,Location,Price
0,5TDYK3DC2FS683067,Toyota,Sienna,XLE 8-Passenger FWD,2015,"51,825",18,25,3.5,Automatic,FWD,Gas,Gray,Gray,0,2,Personal use,"Clayton, ID","27,999"
1,5XYPG4A31KG450330,Kia,Sorento,LX I4 FWD,2019,"68,125",22,29,2.4,Automatic,FWD,Gas,Gray,Black,1,2,Fleet use,"Santa Ana, CA","22,779"
2,1GNSKCKJ2KR159005,Chevrolet,Tahoe,Premier 4WD,2019,"28,170",15,21,6.2,Automatic,4WD,Gas,White,Black,0,1,Personal use,"Pelham, AL","61,990"
3,1FMCU0GD4JUA78698,Ford,Escape,SE FWD,2018,"138,293",23,30,1.5,Automatic,FWD,Gas,White,Gray,0,1,Personal use,"Melbourne, FL","12,998"
4,1FTEW1E55JKC28614,Ford,F-150,XL SuperCrew 5.5' Box 4WD,2018,"120,532",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Plano, TX","21,900"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,1N4BL4BV2LC229210,Nissan,Altima,2.5 S FWD,2020,"48,887",28,39,2.5,Automatic,FWD,Gas,Silver,Black,0,1,Personal use,"Leesburg, FL","19,888"
197,1FTEW1E87HKD75473,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2017,"216,301",17,23,3.5,Automatic,4WD,Gas,White,Gray,0,2,Personal use,"Colorado Springs, CO","16,990"
198,1FTEW1E5XJFA09401,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2018,"51,273",18,23,5.0,Automatic,4WD,Gas,White,Gray,0,1,Personal use,"Pasadena, TX","30,683"
199,1GNSKBKC5KR120047,Chevrolet,Tahoe,LT 4WD,2019,"69,974",15,21,5.3,Automatic,4WD,Gas,Black,Black,1,3,Personal use,"Lubbock, TX","27,518"
200,3GNAXJEVXKS636390,Chevrolet,Equinox,LT with 2FL FWD,2019,"32,159",26,32,1.5,Automatic,FWD,Gas,White,Black,1,1,Personal use,"Las Vegas, NV","20,500"