# DATA 606 FINAL PROJECT
### WEBSCRAPING THE WEBSITE 'TRUECAR.COM' FOR GETTING THE DATA OF USED CARS

### Importing required packages for scraping

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import lxml.html as lxl
import numpy as np

### Accessing the cars.com website and walking through different pages in the website

In [2]:
pages=[]
base_url = 'https://www.truecar.com/used-cars-for-sale/listings/'
for i in range(100):
        pages.append(base_url + '?page=' + str(i))

In [3]:
pages

['https://www.truecar.com/used-cars-for-sale/listings/?page=0',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=1',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=2',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=3',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=4',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=5',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=6',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=7',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=8',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=9',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=10',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=11',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=12',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=13',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=14',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=15',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=16',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=17',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=18',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=19',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=20',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=21',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=22',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=23',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=24',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=25',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=26',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=27',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=28',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=29',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=30',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=31',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=32',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=33',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=34',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=35',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=36',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=37',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=38',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=39',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=40',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=41',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=42',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=43',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=44',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=45',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=46',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=47',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=48',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=49',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=50',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=51',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=52',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=53',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=54',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=55',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=56',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=57',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=58',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=59',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=60',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=61',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=62',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=63',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=64',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=65',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=66',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=67',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=68',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=69',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=70',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=71',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=72',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=73',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=74',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=75',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=76',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=77',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=78',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=79',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=80',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=81',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=82',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=83',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=84',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=85',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=86',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=87',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=88',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=89',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=90',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=91',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=92',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=93',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=94',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=95',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=96',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=97',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=98',
 'https://www.truecar.com/used-cars-for-sale/listings/?page=99']

### Accessing link of each car for sale

In [4]:
%%time
base_url = 'https://www.truecar.com/'
all_cars_urls = []
for link in pages:
    req = requests.get(link)

    soup = BeautifulSoup(req.text,'html.parser')

    req_links = soup.find_all('a')
    
    for link in req_links:
        suffix = str(link.get('href'))
        if ('used-cars-for-sale/listing/' in suffix):
            car_url = base_url + suffix
            all_cars_urls.append(car_url)

CPU times: user 17.7 s, sys: 245 ms, total: 17.9 s
Wall time: 2min 44s

### Formatting the obtained links to avoid duplicates

In [5]:
set_all_cars_urls = set(all_cars_urls)
n_urls = list(set_all_cars_urls)
len(n_urls)

2976

### Website links of all the existing cars

In [6]:
urls=n_urls[:]
urls[:10]

['https://www.truecar.com//used-cars-for-sale/listing/JTHBK1EG8C2504415/2012-lexus-es/',
 'https://www.truecar.com//used-cars-for-sale/listing/1FT8W3BT0DEA39447/2013-ford-super-duty-f-350/',
 'https://www.truecar.com//used-cars-for-sale/listing/KL4CJASB1KB777593/2019-buick-encore/',
 'https://www.truecar.com//used-cars-for-sale/listing/1HGCV1F31JA003377/2018-honda-accord/',
 'https://www.truecar.com//used-cars-for-sale/listing/1C4HJXEG3JW160547/2018-jeep-wrangler/',
 'https://www.truecar.com//used-cars-for-sale/listing/1FAFP53U25A225965/2005-ford-taurus/',
 'https://www.truecar.com//used-cars-for-sale/listing/1FTFW1EG5JFA74484/2018-ford-f-150/',
 'https://www.truecar.com//used-cars-for-sale/listing/1FMCU9GD1JUA39118/2018-ford-escape/',
 'https://www.truecar.com//used-cars-for-sale/listing/1GYKNCRS2KZ116812/2019-cadillac-xt5/',
 'https://www.truecar.com//used-cars-for-sale/listing/1N4BL4BV3LC157496/2020-nissan-altima/']

### Finding the attributes of the datasets using Beautiful Soup

In [7]:
output_details=soup.find_all('div', {'class': 'vehicle-card'})
len(output_details)

30

In [8]:
output_details[0]

<div class="linkable card card-shadow vehicle-card _1qd1muk" data-test="usedListing" data-test-dealerid="12046" data-test-item="1FTFW1CT8EFC74622"><div class="carousel w-100 position-relative"><div class="d-flex align-items-center w-100 position-relative"><button aria-label="Previous" class="carousel-arrow carousel-arrow-inside carousel-arrow-light carousel-arrow-small carousel-arrow-slide-spacing-0 carousel-arrow-prev carousel-arrow-prev carousel-arrow-vehicle-card-challenger-button carousel-arrow-vehicle-card-challenger-button-prev" data-test="carouselArrowPrev" disabled=""><svg class="carousel-arrow-icon carousel-arrow-vehicle-card-challenger-button-icon" height="16px" viewbox="0 0 16 16" width="16px"><g fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-width="1"><polyline fill-rule="nonzero" points="5 2 12 8.36363636 5 14.7272727" stroke-width="1.5"></polyline></g></svg></button><div class="flex-grow-1" style="position:relative;overflow:hidden"><ul class="" data-test="carouselSlideContainer" style="display:flex;flex-flow:row nowrap;position:relative;overflow-y:hidden;overflow-x:hidden"><li class="" data-test="carouselCurrentSlide0" style="scroll-snap-align:start;flex-shrink:0;width:100%"><a aria-hidden="true" class="linkable vehicle-card-challenger-image-link" data-test="vehicleCardImageLink" href="/used-cars-for-sale/listing/1FTFW1CT8EFC74622/2014-ford-f-150/" tabindex="-1"><div class="card-image vehicle-card-image"><div class="img-container img-container-block" style="height:auto;padding-bottom:56.56250000000001%;width:100%"><img alt="" class="img-inner img-block img-crop" loading="eager" role="presentation" sizes="300px" src="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/LCLJPWY3I36MSRUO3KO7WOQ4YI-cr-120.jpg" srcset="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/LCLJPWY3I36MSRUO3KO7WOQ4YI-cr-120.jpg 120w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/LCLJPWY3I36MSRUO3KO7WOQ4YI-cr-360.jpg 360w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/LCLJPWY3I36MSRUO3KO7WOQ4YI-cr-540.jpg 540w" style="background-image:url(https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/LCLJPWY3I36MSRUO3KO7WOQ4YI-cr-360.jpg)"/></div></div></a></li><li class="" data-test="" style="scroll-snap-align:start;flex-shrink:0;width:100%"><a aria-hidden="true" class="linkable vehicle-card-challenger-image-link" data-test="vehicleCardImageLink" href="/used-cars-for-sale/listing/1FTFW1CT8EFC74622/2014-ford-f-150/" tabindex="-1"><div class="card-image vehicle-card-image"><div class="img-container img-container-block" style="height:auto;padding-bottom:56.56250000000001%;width:100%"><img alt="" class="img-inner img-block img-crop" loading="eager" role="presentation" sizes="300px" src="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/RSZQDUYIQ77VDGJOHHYBCYZMIU-cr-120.jpg" srcset="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/RSZQDUYIQ77VDGJOHHYBCYZMIU-cr-120.jpg 120w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/RSZQDUYIQ77VDGJOHHYBCYZMIU-cr-360.jpg 360w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/RSZQDUYIQ77VDGJOHHYBCYZMIU-cr-540.jpg 540w" style="background-image:url(https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/RSZQDUYIQ77VDGJOHHYBCYZMIU-cr-360.jpg)"/></div></div></a></li><li class="" data-test="" style="scroll-snap-align:start;flex-shrink:0;width:100%"><a aria-hidden="true" class="linkable vehicle-card-challenger-image-link" data-test="vehicleCardImageLink" href="/used-cars-for-sale/listing/1FTFW1CT8EFC74622/2014-ford-f-150/" tabindex="-1"><div class="card-image vehicle-card-image"><div class="img-container img-container-block" style="height:auto;padding-bottom:56.56250000000001%;width:100%"><img alt="" class="img-inner img-block img-crop" loading="eager" role="presentation" sizes="300px" src="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/ROBY4LEPHJAJNXUHPAWSLXIVOU-cr-120.jpg" srcset="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/ROBY4LEPHJAJNXUHPAWSLXIVOU-cr-120.jpg 120w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/ROBY4LEPHJAJNXUHPAWSLXIVOU-cr-360.jpg 360w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/ROBY4LEPHJAJNXUHPAWSLXIVOU-cr-540.jpg 540w" style="background-image:url(https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/ROBY4LEPHJAJNXUHPAWSLXIVOU-cr-360.jpg)"/></div></div></a></li><li class="" data-test="" style="scroll-snap-align:start;flex-shrink:0;width:100%"><a aria-hidden="true" class="linkable vehicle-card-challenger-image-link" data-test="vehicleCardImageLink" href="/used-cars-for-sale/listing/1FTFW1CT8EFC74622/2014-ford-f-150/" tabindex="-1"><div class="card-image vehicle-card-image"><div class="img-container img-container-block" style="height:auto;padding-bottom:56.56250000000001%;width:100%"><img alt="" class="img-inner img-block img-crop" loading="eager" role="presentation" sizes="300px" src="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/T5O43VBJOSIMU2NOHLYHDIYMVM-cr-120.jpg" srcset="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/T5O43VBJOSIMU2NOHLYHDIYMVM-cr-120.jpg 120w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/T5O43VBJOSIMU2NOHLYHDIYMVM-cr-360.jpg 360w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/T5O43VBJOSIMU2NOHLYHDIYMVM-cr-540.jpg 540w" style="background-image:url(https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/T5O43VBJOSIMU2NOHLYHDIYMVM-cr-360.jpg)"/></div></div></a></li><li class="" data-test="" style="scroll-snap-align:start;flex-shrink:0;width:100%"><a aria-hidden="true" class="linkable vehicle-card-challenger-image-link" data-test="vehicleCardImageLink" href="/used-cars-for-sale/listing/1FTFW1CT8EFC74622/2014-ford-f-150/" tabindex="-1"><div class="card-image vehicle-card-image"><div class="img-container img-container-block" style="height:auto;padding-bottom:56.56250000000001%;width:100%"><img alt="" class="img-inner img-block img-crop" loading="eager" role="presentation" sizes="300px" src="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/FY7YKQH4BXUKW5NZDTF6B6LLH4-cr-120.jpg" srcset="https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/FY7YKQH4BXUKW5NZDTF6B6LLH4-cr-120.jpg 120w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/FY7YKQH4BXUKW5NZDTF6B6LLH4-cr-360.jpg 360w,https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/FY7YKQH4BXUKW5NZDTF6B6LLH4-cr-540.jpg 540w" style="background-image:url(https://listings-prod.tcimg.net/listings/12046/22/46/1FTFW1CT8EFC74622/FY7YKQH4BXUKW5NZDTF6B6LLH4-cr-360.jpg)"/></div></div></a></li></ul></div><button aria-label="Next" class="carousel-arrow carousel-arrow-inside carousel-arrow-light carousel-arrow-small carousel-arrow-slide-spacing-0 carousel-arrow-next carousel-arrow-next carousel-arrow-vehicle-card-challenger-button carousel-arrow-vehicle-card-challenger-button-next" data-test="carouselArrowNext"><svg class="carousel-arrow-icon carousel-arrow-vehicle-card-challenger-button-icon" height="16px" viewbox="0 0 16 16" width="16px"><g fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-width="1"><polyline fill-rule="nonzero" points="5 2 12 8.36363636 5 14.7272727" stroke-width="1.5"></polyline></g></svg></button></div><ul class="carousel-dots-container vehicle-card-challenger-carousel-dots" data-test="carouselDots"><li class="carousel-dots-dot-selected" data-qa="CarouselDots-dot" data-test="carouselDotsDot"></li><li class="carousel-dots-dot-unselected-dark" data-qa="CarouselDots-dot" data-test="carouselDotsDot"></li><li class="carousel-dots-dot-unselected-dark" data-qa="CarouselDots-dot" data-test="carouselDotsDot"></li><li class="carousel-dots-dot-unselected-dark" data-qa="CarouselDots-dot" data-test="carouselDotsDot"></li><li class="carousel-dots-dot-unselected-dark" data-qa="CarouselDots-dot" data-test="carouselDotsDot"></li></ul></div><div class="vehicle-card-image-overlay order-1"><button aria-label="Add this car to favorites" aria-pressed="false" class="btn-round like-button like-button-xs vehicle-card-like-button shadow shadow-hover btn btn-muted btn-xs" data-ignore-contrast="false" data-loading="false" data-test="saveVehicle" name="Save this vehicle" type="button"><span class="btn-inner"><svg class="icon like-button-icon icon-color-default" style="width:16px;height:16px;stroke-width:1.5" viewbox="0 0 24 24"><path d="M22.13 9.09a5.4 5.4 0 00-9.63-3.37 5.4 5.4 0 00-9.63 3.37 6.26 6.26 0 001.81 4h0l7.83 8.61 7.67-8.46.14-.15a6.29 6.29 0 001.81-4z"></path></svg></span></button></div><div class="card-content vehicle-card-body order-3 vehicle-card-challenger-body" data-test="cardContent"><a aria-label="View details for 2014 Ford F-150" class="linkable order-2 vehicle-card-overlay" data-test="vehicleCardLink" href="/used-cars-for-sale/listing/1FTFW1CT8EFC74622/2014-ford-f-150/"></a><div class="vehicle-card-top"><h3 class="heading-base" data-qa="Heading" data-test="vehicleListingCardTitle"><div class="vehicle-card-header w-100" data-test="vehicleCardYearMakeModel"><span class="vehicle-card-year font-size-1">2014</span> <span class="vehicle-header-make-model text-truncate">Ford<!-- --> <!-- -->F-150</span></div><div class="font-size-1 text-truncate" data-test="vehicleCardTrim">XLT SuperCrew 5.5' Box RWD</div></h3></div><div class="vehicle-card-bottom vehicle-card-bottom-top-spacing"><div class="d-flex w-100 vehicle-card-bottom-pricing justify-content-between" style="min-height:43px"><div class="padding-right-3 vehicle-card-bottom-pricing-primary"><div class="font-size-2"><div class=""><div class="vehicle-card-price-rating-label-container"><div class="graph-icon-container graph-icon-bucket-one vehicle-card-price-rating-label-icon-container" style="height:1rem;width:1rem"><svg class="icon graph-icon undefined icon-fill-default" style="width:8px;height:8px;stroke-width:3" viewbox="0 0 24 24"><g fill-rule="evenodd"><path d="M12 24l10-10H2zM12 10L22 0H2z"></path></g></svg></div><span class="graph-icon-title margin-left-1 vehicle-card-price-rating-label text-truncate font-weight-bold" data-test="graphIconLabel">Excellent Price</span></div></div><div class="font-size-1 text-truncate">$<!-- -->1,131<!-- --> <!-- -->off<!-- --> <!-- -->avg. list price</div></div></div><div class="padding-left-3 padding-left-lg-2 vehicle-card-bottom-pricing-secondary vehicle-card-bottom-max-50"><div data-test="vehicleListingPriceAmount"><div class="heading-3 margin-y-1 font-weight-bold" data-qa="Heading" data-test="vehicleCardPricingBlockPrice">$12,995</div></div></div></div></div><div class="margin-top-2_5 padding-top-2_5 border-top w-100"><div class="d-flex w-100 justify-content-between"><div class="font-size-1 text-truncate" data-test="vehicleMileage"><svg class="icon icon-before vehicle-card-icon icon-color-default" style="width:16px;height:16px;stroke-width:1.5" viewbox="0 0 24 24"><path d="M.28 15.67l2.68.19M1.04 12.26l2.59 1M2.77 9.22l2.24 1.76M5.32 6.82l1.57 2.26M8.47 5.28l3.21 10.58M11.92 4.74l.02 2.9M15.38 5.23l-.83 2.79M18.55 6.73l-1.62 2.41M21.13 9.09l-2.24 1.81M22.91 12.1l-2.64 1.06M23.72 15.5l-2.8.24"></path><circle cx="11.92" cy="16.64" r=".87"></circle></svg>222,150<!-- --> miles</div></div><div class="vehicle-card-location font-size-1 margin-top-1" data-test="vehicleCardLocation"><svg class="icon icon-before vehicle-card-icon icon-color-default" style="width:16px;height:16px;stroke-width:1.5" viewbox="0 0 24 24"><circle cx="12.03" cy="9.02" r="3.5"></circle><path d="M20.53 9c0 6.5-8 14.5-8.5 14.5s-8.5-8-8.5-14.5a8.5 8.5 0 0117 0z"></path></svg>Pembroke Pines<!-- -->, <!-- -->FL</div><div class="vehicle-card-location font-size-1 margin-top-1 text-truncate" data-test="vehicleCardColors"><svg class="icon icon-before vehicle-card-icon icon-color-default" style="width:16px;height:16px;stroke-width:1.5" viewbox="0 0 24 24"><path d="M18.45 18.94l2.13-3.61 2.16 3.65"></path><path d="M22.67 18.86a2.54 2.54 0 01.46 1.33v.13a2.55 2.55 0 11-5.1 0v-.23a2.54 2.54 0 01.46-1.24"></path><circle cx="14.5" cy="9.5" r="1"></circle><path d="M20.42 12.26L10.33 22.35 1.3 13.31 11.39 3.22M14.5 9V1M10.64 2.09l10.84 10.84"></path></svg>Red<!-- --> exterior, <!-- -->Gray<!-- --> interior</div></div><div class="vehicle-card-location font-size-1 margin-top-1" data-test="vehicleCardCondition"><svg class="icon icon-before vehicle-card-icon icon-color-default" style="width:16px;height:16px;stroke-width:1.5" viewbox="0 0 24 24"><path d="M22 13.13v6.23a.7.7 0 01-.68.72h-2.71a.69.69 0 01-.65-.72v-1.28H6v1.28a.69.69 0 01-.65.72H2.64a.7.7 0 01-.64-.72v-5.91a2.84 2.84 0 01.34-1.35l2.09-4A3.76 3.76 0 017.6 6.08H17a3.79 3.79 0 013.4 2.47L21.75 12a2.93 2.93 0 01.25 1.13z"></path><path d="M7.96 14.08h-3"></path><path d="M2.83 11.08H.46M23.46 11.08h-2.09M18.46 11.08h-13"></path><path d="M18.96 14.08h-3"></path></svg>No accidents, 2 Owners, Personal use</div><div class="font-size-1 margin-top-1"><svg class="icon icon-before vehicle-card-icon icon-fill-default" style="width:16px;height:16px;stroke-width:1.5" viewbox="0 0 24 24"><path d="M8 .5a.5.5 0 01.5.5v.5h3V1a.5.5 0 011 0v.5h3V1a.5.5 0 011 0v.5H19c.414 0 .797.14 1.079.421.28.282.421.665.421 1.079v19c0 .414-.14.797-.421 1.079-.282.28-.665.421-1.079.421H5c-.414 0-.797-.14-1.079-.421-.28-.282-.421-.665-.421-1.079V3c0-.414.14-.797.421-1.079.282-.28.665-.421 1.079-.421h2.5V1A.5.5 0 018 .5zm-.5 2H5c-.186 0-.303.06-.371.129-.07.068-.129.185-.129.371v19c0 .186.06.303.129.371.068.07.185.129.371.129h14c.186 0 .303-.06.371-.129.07-.068.129-.185.129-.371V3c0-.186-.06-.303-.129-.371-.068-.07-.185-.129-.371-.129h-2.5V4a.5.5 0 01-1 0V2.5h-3V4a.5.5 0 01-1 0V2.5h-3V4a.5.5 0 01-1 0V2.5zM6.4 8.3H18v1H6.4v-1zm0 3H18v1H6.4v-1zm0 3H18v1H6.4v-1zm0 3H13v1H6.4v-1z" fill-rule="evenodd"></path></svg>MPG: 17-23, Engine: 3.5L V-6 Gas Turbocharged, Transmission: Automatic, RWD</div><div class="font-size-1 vehicle-card-vin-challenger">VIN: <!-- -->1FTFW1CT8EFC74622</div></div></div>

In [9]:
output_details[17].find('span',{'class':"vehicle-header-make-model text-truncate"}).get_text()

'Chrysler Pacifica'

In [10]:
output_details[17].find('span',{'class':"vehicle-card-year font-size-1"}).get_text()

'2020'

In [11]:
output_details[0].find('div',{'class':"font-size-1 text-truncate"}).get_text()

"XLT SuperCrew 5.5' Box RWD"

In [12]:
output_details[17].find('div',{'data-test':"vehicleMileage"}).get_text()

'66,328 miles'

In [13]:
output_details[0].find('div',{'data-test':"vehicleListingPriceAmount"}).get_text()

'$12,995'

In [14]:
output_details[21].find('div',{'class':"font-size-1 margin-top-1"}).get_text()

'MPG: 26-32, Engine: 1.5L Inline-4 Gas Turbocharged, Transmission: Automatic, FWD'

In [15]:
output_details[17].find('div',{'class':"font-size-1 vehicle-card-vin-challenger"}).get_text()

'VIN: 2C4RC1BG5LR269331'

In [16]:
output_details[17].find('div',{'class':"font-size-1 text-truncate"}).get_text()

'Touring L FWD'

In [17]:
output_details[17].find('div',{'data-test':"vehicleCardCondition"}).get_text()

'No accidents, 2 Owners, Personal use'

In [18]:
output_details[17].find('div',{'data-test':"vehicleCardLocation"}).get_text()

'Athens, GA'

In [19]:
output_details[20].find('div',{'class':"vehicle-card-location font-size-1 margin-top-1"}).get_text()

'Hudson, WI'

In [20]:
output_details[2].find('div',{'class':"vehicle-card-location font-size-1 margin-top-1 text-truncate"}).get_text()

'White exterior, Gray interior'

In [21]:
output_details[11].find('div',{'data-test':"cardContent"}).get_text()

'2018 Ford EscapeSE 4WDExcellent Price$792 off avg. list price$18,92065,186 milesDiscount AvailablePrince Frederick, MDWhite exterior, Black interiorNo accidents, 1 Owner, Personal useMPG: 22-28, Engine: 1.5L Inline-4 Gas Turbocharged, Transmission: Automatic, 4WDVIN: 1FMCU9GD1JUA39118'

### Adopting the columns for creating a dataframe

In [22]:
make=[]
model=[]
trim=[]
year = []

mileage = []

location = []

engine=[]
transmission=[]
drive_type=[]
price = []
exterior_color=[]
interior_color=[]
vehicle_history=[]
MPG_city=[]
MPG_highway=[]
VIN=[]
accidents =[]
owners=[]
car_usage_type=[]
fuel_type=[]

i=0
for output in output_details:
    

    current_car = output.find('span',{'class':"vehicle-header-make-model text-truncate"}).get_text()
    
    try:
        make.append(current_car.split(' ')[0])
    except:
        make.append('n/a')
    
    try:
        model.append(current_car.split(' ')[1])
    except:
        model.append('n/a')
    
    try:
        trim.append(output.find('div',{'class':"font-size-1 text-truncate"}).get_text())
        
    except:
        trim.append('n/a')
    
    try:
        year.append(output.find('span',{'class':"vehicle-card-year font-size-1"}).get_text())
    except:
        year.append('n/a')
        
          
        
    # mileage
    try:
        mileage.append(output.find('div',{'data-test':"vehicleMileage"}).get_text())
    except:
        mileage.append('n/a')
    
        
    try:
        location.append(output.find('div',{'data-test':"vehicleCardLocation"}).get_text())
    except:
        location.append('n/a')    
        
    
    #price 
    try:
        price.append(output.find('div',{'data-test':"vehicleListingPriceAmount"}).get_text())
    except:
        price.append('n/a')
        
    clr=output.find('div',{'class':"vehicle-card-location font-size-1 margin-top-1 text-truncate"}).get_text()
    
    try:
        exterior_color.append(clr.split(',')[0].split(' ')[0])
    except:
        exterior_color.append('n/a')
    
    try:
        interior_color.append(clr.split(',')[1].split(' ')[1])
    except:
        interior_color.append('n/a')
    
    vhkl_hist=output.find('div',{'data-test':"vehicleCardCondition"}).get_text()
    
    try:
        accidents.append(vhkl_hist.split(',')[0])
    except:
        accidents.append('n/a')
        
    try:
        owners.append(vhkl_hist.split(',')[1])
    except:
        owners.append('n/a')
        
    try:
        car_usage_type.append(vhkl_hist.split(',')[2])
    except:
        car_usage_type.append('n/a')
        
        
    met = output.find('div',{'class':"font-size-1 margin-top-1"}).get_text()
    
    try:
        MPG_city.append(((met.split(',')[0]).split(':')[1]).split('-')[0])
    except:
        MPG_city.append('n/a')
        
    try:
        MPG_highway.append(((met.split(',')[0]).split(':')[1]).split('-')[1])
    except:
        MPG_highway.append('n/a')
        
    try:
        engine.append((met.split(',')[1]).split(':')[1])
    except:
        engine.append('n/a')
        
    try:
        transmission.append((met.split(',')[2]).split(':')[1])
    except:
        transmission.append('n/a')
        
    try:
        drive_type.append((met.split(',')[-1]))
    except:
        drive_type.append('n/a')
        
    try:
        ft=((met.split(',')[1]).split(':')[1]).split(' ')
        if ft[-1]=='Turbocharged' or ft[-1]=='Twin-Turbo':
            fuel_type.append(ft[-2])
        else: 
            fuel_type.append(ft[-1])
    except:
        fuel_type.append('n/a')
        
    try:
        VIN.append((output.find('div',{'class':"font-size-1 vehicle-card-vin-challenger"}).get_text()).split(':')[1])
    except:
        VIN.append('n/a')

### Obtaining the values of the dataset with results of one page list

In [23]:

Used_Cars = pd.DataFrame({'Brand': make, 'Model': model, 'Trim' : trim, 'Manufature Year': year, 'Location':location, 
                          'Exterior Color' : exterior_color, 'Interior Color' : interior_color, 'Accidents':accidents,
                          'Owners':owners,'Car Usage Type':car_usage_type,'MPG City': MPG_city, 'MPG Highway':MPG_highway,
                          'Engine':engine, 'Transmission': transmission,'Drive type' : drive_type, 'Fuel Type': fuel_type, 'VIN':VIN, 'Mileage':mileage,'Price': price})

In [24]:
Used_Cars

,Brand,Model,Trim,Manufature Year,Location,Exterior Color,Interior Color,Accidents,Owners,Car Usage Type,MPG City,MPG Highway,Engine,Transmission,Drive type,Fuel Type,VIN,Mileage,Price
0,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"Pembroke Pines, FL",Red,Gray,No accidents,2 Owners,Personal use,17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,1FTFW1CT8EFC74622,"222,150 miles","$12,995"
1,Nissan,Sentra,S CVT,2017,"Bourbonnais, IL",White,Black,1 accident,2 Owners,Personal use,29,37,1.8L Inline-4 Gas,Automatic,FWD,Gas,3N1AB7AP7HY219190,"140,062 miles","$8,900"
2,Ford,Super,XL Crew Cab 8' Box 2WD,2022,"Odessa, TX",White,Gray,No accidents,1 Owner,Personal use,6.2L V,8 Gas,Automatic,n/a,RWD,Automatic,1FT7W2A67NEC61857,"32,089 miles","$48,987"
3,Mercedes-Benz,S-Class,S 550 4MATIC Coupe,2016,"Duluth, GA",Gray,Red,No accidents,2 Owners,Personal use,16,24,4.6L V-8 Gas Turbocharged,Automatic,AWD,Gas,WDDXJ8FB6GA015695,"17,034 miles","$72,988"
4,Nissan,Rogue,SV AWD,2018,"Manassas, VA",Blue,Black,No accidents,2 Owners,Fleet use,25,32,2.5L Inline-4 Gas,Automatic,AWD,Gas,5N1AT2MV4JC726551,"51,138 miles","$20,995"
5,Toyota,Camry,SE FWD Automatic,2020,"Cornelius, NC",White,Black,1 accident,1 Owner,Personal use,28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,4T1G11AK3LU926676,"62,598 miles","$25,599"
6,Chevrolet,Equinox,LT with 1LT FWD,2020,"Burlington, NJ",Blue,Black,No accidents,1 Owner,Personal use,26,32,1.5L Inline-4 Gas Turbocharged,Automatic,FWD,Gas,3GNAXKEV7LS509278,"64,324 miles","$19,998"
7,Ford,F-150,XLT SuperCab 6.5' Box 4WD,2013,"Braintree, MA",Blue,Gray,No accidents,4 Owners,Fleet use,16,21,3.5L V-6 Gas Turbocharged,Automatic,4WD,Gas,1FTFX1ETXDFB63305,"84,134 miles","$18,500"
8,Jeep,Wrangler,Unlimited Rubicon (JK),2018,"Longmont, CO",Gray,Black,No accidents,1 Owner,Personal use,16,21,3.6L V-6 Gas,Automatic,4WD,Gas,1C4BJWFG9JL884291,"26,926 miles","$39,998"
9,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2013,"Mesa, AZ",Black,Gray,No accidents,1 Owner,Personal use,14,19,5.0L V-8 Gas,Automatic,4WD,Gas,1FTFW1EF1DFB86064,"94,325 miles","$22,499"
10,Hyundai,Elantra,SEL 2.0L IVT,2020,"Tampa, FL",Silver,Black,No accidents,1 Owner,Personal use,30,40,2.0L Inline-4 Gas,Automatic,FWD,Gas,5NPD84LF2LH527711,"60,290 miles","$18,034"
11,Ford,Escape,SE 4WD,2018,"Prince Frederick, MD",White,Black,No accidents,1 Owner,Personal use,22,28,1.5L Inline-4 Gas Turbocharged,Automatic,4WD,Gas,1FMCU9GD1JUA39118,"65,186 miles","$18,920"
12,Hyundai,Elantra,SEL 2.0L IVT,2020,"Houston, TX",Gray,Black,No accidents,1 Owner,Personal use,30,40,2.0L Inline-4 Gas,Automatic,FWD,Gas,5NPD84LF6LH536380,"65,024 miles","$20,045"
13,Volvo,XC60,T5 Momentum AWD,2019,"San Antonio, TX",White,Black,No accidents,1 Owner,Personal use,n/a,n/a,n/a,n/a,Certified Pre-Owned,n/a,LYV102RK5KB237836,"20,474 miles","$36,962"
14,Ford,Mustang,V6 Coupe,2014,"Temple, TX",Green,Unknown,2 accidents,4 Owners,Fleet use,19,29,3.7L V-6 Gas,Automatic,RWD,Gas,1ZVBP8AM1E5201580,"152,755 miles","$11,000"
15,Honda,Pilot,EX-L FWD,2021,"Longview, TX",Black,Unknown,No accidents,1 Owner,Personal use,n/a,n/a,n/a,n/a,Certified Pre-Owned,n/a,5FNYF5H50MB006094,"33,169 miles","$37,581"
16,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2021,"Kent, WA",White,Black,No accidents,0 Owners,Personal use,19,22,2.7L V-6 Gas Turbocharged,Automatic,4WD,Gas,1FTEW1EP7MKD88497,"9,684 miles","$48,900"
17,Chrysler,Pacifica,Touring L FWD,2020,"Athens, GA",Gray,Black,No accidents,2 Owners,Personal use,19,28,3.6L V-6 Gas,Automatic,FWD,Gas,2C4RC1BG5LR269331,"66,328 miles","$25,488"
18,Ford,Fusion,SE FWD,2016,"Littleton, CO",Gray,Gray,No accidents,4 Owners,Fleet use,22,34,2.5L Inline-4 Gas,Automatic,FWD,Gas,3FA6P0H78GR175118,"93,829 miles","$13,489"
19,Ford,Expedition,XLT 4WD,2017,"Bend, OR",Blue,Unknown,No accidents,2 Owners,Fleet use,15,20,3.5L V-6 Gas Turbocharged,Automatic,4WD,Gas,1FMJU1JT0HEA28947,"66,420 miles","$29,990"
20,Ford,Explorer,XLT 4WD,2020,"Hudson, WI",Black,Black,No accidents,1 Owner,Personal use,20,27,2.3L Inline-4 Gas Turbocharged,Automatic,4WD,Gas,1FMSK8DH3LGD17103,"17,630 miles","$39,995"
21,Chevrolet,Equinox,LT with 1LT FWD,2020,"Sanford, FL",Silver,Black,1 accident,2 Owners,Personal use,26,32,1.5L Inline-4 Gas Turbocharged,Automatic,FWD,Gas,3GNAXKEV0LS516279,"35,582 miles","$23,590"
22,Chevrolet,Malibu,LT,2020,"Fredericksburg, VA",Black,Black,No accidents,1 Owner,Personal use,n/a,n/a,n/a,n/a,Certified Pre-Owned,n/a,1G1ZD5ST3LF118439,"49,447 miles","$23,900"
23,Ford,F-150,Lariat SuperCrew 5.5' Box 4WD,2019,"Hazelwood, MO",White,Black,No accidents,1 Owner,Personal use,19,24,2.7L V-6 Gas Turbocharged,Automatic,4WD,Gas,1FTEW1EP9KKC25959,"50,561 miles","$39,990"
24,Ford,Mustang,2dr Coupe Premium,2005,"Austin, TX",Silver,Black,1 accident,5 Owners,Personal use,19,28,4.0L V-6 Gas,Automatic,RWD,Gas,1ZVFT80NX55102814,"174,987 miles","$6,499"
25,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2014,"Van Nuys, CA",White,Black,No accidents,1 Owner,Personal use,14,19,5.0L V-8 Gas,Automatic,4WD,Gas,1FTFW1EF4EFB51083,"99,989 miles","$20,988"
26,Ford,Super,Lariat 4WD Crew Cab 6.75' Box,2019,"Waco, TX",Gray,Black,No accidents,1 Owner,Personal use,6.7L V,8 Diesel Turbocharged,Automatic,n/a,4WD,Automatic,1FT7W2BT5KEF00323,"29,594 miles","$67,995"
27,Nissan,Altima,2.5 S FWD,2020,"Ocala, FL",Gray,Black,1 accident,1 Owner,Personal use,28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,1N4BL4BV0LC207822,"62,595 miles","$19,792"
28,Dodge,Grand,SE,2019,"Wenatchee, WA",Silver,Black,No accidents,2 Owners,Fleet use,17,25,3.6L V-6 Gas,Automatic,FWD,Gas,2C4RDGBG7KR591208,"124,972 miles","$16,995"
29,BMW,X1,xDrive28i AWD,2018,"Reno, NV",White,Beige,1 accident,2 Owners,Personal use,22,31,2.0L Inline-4 Gas Turbocharged,Automatic,AWD,Gas,WBXHT3C35J5K31260,"60,601 miles","$26,999"

### Following the same method to obtain all the values of the details of cars on the website

In [25]:
make=[]
model=[]
trim=[]
year = []

mileage = []

location = []

engine=[]
transmission=[]
drive_type=[]
price = []
exterior_color=[]
interior_color=[]
vehicle_history=[]
MPG_city=[]
MPG_highway=[]
VIN=[]
accidents =[]
owners=[]
car_usage_type=[]
fuel_type=[]

filename = 'Used Cars Prices_TRUECAR'

for i in range (1,550):
    
    
    for output in output_details:
    
 
        current_car = output.find('span',{'class':"vehicle-header-make-model text-truncate"}).get_text()
    
        try:
            make.append(current_car.split(' ')[0])
        except:
            make.append('n/a')
    
        try:
            model.append(current_car.split(' ')[1])
        except:
            model.append('n/a')
    
        try:
            trim.append(output.find('div',{'class':"font-size-1 text-truncate"}).get_text())
        
        except:
            trim.append('n/a')
    
        try:
            year.append(output.find('span',{'class':"vehicle-card-year font-size-1"}).get_text())
        except:
            year.append('n/a')
        
          
        
    # mileage
        try:
            mileage.append(output.find('div',{'data-test':"vehicleMileage"}).get_text())
        except:
            mileage.append('n/a')
    
        
        try:
            location.append(output.find('div',{'data-test':"vehicleCardLocation"}).get_text())
        except:
            location.append('n/a')    
        
    
    #price 
        try:
            price.append(output.find('div',{'data-test':"vehicleListingPriceAmount"}).get_text())
        except:
            price.append('n/a')
        
        
        clr=output.find('div',{'class':"vehicle-card-location font-size-1 margin-top-1 text-truncate"}).get_text()
    
        try:
            exterior_color.append(clr.split(',')[0].split(' ')[0])
        except:
            exterior_color.append('n/a')
    
        try:
            interior_color.append(clr.split(',')[1].split(' ')[1])
        except:
            interior_color.append('n/a')
        
        vhkl_hist=output.find('div',{'data-test':"vehicleCardCondition"}).get_text()
    
        try:
            accidents.append(vhkl_hist.split(',')[0])
        except:
            accidents.append('n/a')
        
        try:
            owners.append(vhkl_hist.split(',')[1])
        except:
            owners.append('n/a')
        
        try:
            car_usage_type.append(vhkl_hist.split(',')[2])
        except:
            car_usage_type.append('n/a')
        
        
        met = output.find('div',{'class':"font-size-1 margin-top-1"}).get_text()
    
        try:
            MPG_city.append(((met.split(',')[0]).split(':')[1]).split('-')[0])
        except:
            MPG_city.append('n/a')
        
        try:
            MPG_highway.append(((met.split(',')[0]).split(':')[1]).split('-')[1])
        except:
            MPG_highway.append('n/a')
        
        try:
            engine.append((met.split(',')[1]).split(':')[1])
        except:
            engine.append('n/a')
        
        try:
            transmission.append((met.split(',')[2]).split(':')[1])
        except:
            transmission.append('n/a')
            
        try:
            drive_type.append((met.split(',')[-1]))
        except:
            drive_type.append('n/a')
            
        try:
            ft=((met.split(',')[1]).split(':')[1]).split(' ')
            if ft[-1]=='Turbocharged' or ft[-1]=='Twin-Turbo':
                fuel_type.append(ft[-2])
            else: 
                fuel_type.append(ft[-1])
        except:
            fuel_type.append('n/a')
        
        try:
            VIN.append((output.find('div',{'class':"font-size-1 vehicle-card-vin-challenger"}).get_text()).split(':')[1])
        except:
            VIN.append('n/a')

In [26]:

Used_Cars = pd.DataFrame({'VIN':VIN,'Brand': make, 'Model': model, 'Trim' : trim, 'Manufature Year': year,
                          'Mileage':mileage,'MPG City': MPG_city,'MPG Highway':MPG_highway,'Engine':engine, 
                          'Transmission': transmission,'Drive type' : drive_type, 'Fuel Type': fuel_type,
                          'Exterior Color' : exterior_color, 'Interior Color' : interior_color,'Accidents':accidents,
                          'Owners':owners,'Car Usage Type':car_usage_type, 'Location':location,'Price': price})

### Required dataset

In [27]:
Used_Cars.index=Used_Cars.VIN
del Used_Cars['VIN']

In [28]:
Used_Cars

,Brand,Model,Trim,Manufature Year,Mileage,MPG City,MPG Highway,Engine,Transmission,Drive type,Fuel Type,Exterior Color,Interior Color,Accidents,Owners,Car Usage Type,Location,Price
VIN,,,,,,,,,,,,,,,,,,
1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"
3N1AB7AP7HY219190,Nissan,Sentra,S CVT,2017,"140,062 miles",29,37,1.8L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,2 Owners,Personal use,"Bourbonnais, IL","$8,900"
1FT7W2A67NEC61857,Ford,Super,XL Crew Cab 8' Box 2WD,2022,"32,089 miles",6.2L V,8 Gas,Automatic,n/a,RWD,Automatic,White,Gray,No accidents,1 Owner,Personal use,"Odessa, TX","$48,987"
WDDXJ8FB6GA015695,Mercedes-Benz,S-Class,S 550 4MATIC Coupe,2016,"17,034 miles",16,24,4.6L V-8 Gas Turbocharged,Automatic,AWD,Gas,Gray,Red,No accidents,2 Owners,Personal use,"Duluth, GA","$72,988"
5N1AT2MV4JC726551,Nissan,Rogue,SV AWD,2018,"51,138 miles",25,32,2.5L Inline-4 Gas,Automatic,AWD,Gas,Blue,Black,No accidents,2 Owners,Fleet use,"Manassas, VA","$20,995"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1FTFW1EF4EFB51083,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2014,"99,989 miles",14,19,5.0L V-8 Gas,Automatic,4WD,Gas,White,Black,No accidents,1 Owner,Personal use,"Van Nuys, CA","$20,988"
1FT7W2BT5KEF00323,Ford,Super,Lariat 4WD Crew Cab 6.75' Box,2019,"29,594 miles",6.7L V,8 Diesel Turbocharged,Automatic,n/a,4WD,Automatic,Gray,Black,No accidents,1 Owner,Personal use,"Waco, TX","$67,995"
1N4BL4BV0LC207822,Nissan,Altima,2.5 S FWD,2020,"62,595 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,Gray,Black,1 accident,1 Owner,Personal use,"Ocala, FL","$19,792"
2C4RDGBG7KR591208,Dodge,Grand,SE,2019,"124,972 miles",17,25,3.6L V-6 Gas,Automatic,FWD,Gas,Silver,Black,No accidents,2 Owners,Fleet use,"Wenatchee, WA","$16,995"
WBXHT3C35J5K31260,BMW,X1,xDrive28i AWD,2018,"60,601 miles",22,31,2.0L Inline-4 Gas Turbocharged,Automatic,AWD,Gas,White,Beige,1 accident,2 Owners,Personal use,"Reno, NV","$26,999"

### Converting the dataframe to a csv file for easy access and handling

In [29]:
Used_Cars.to_csv("{}.csv".format(filename))

In [30]:
df = pd.read_csv('Used Cars Prices_TRUECAR.csv', index_col=0)

In [31]:
df

,Brand,Model,Trim,Manufature Year,Mileage,MPG City,MPG Highway,Engine,Transmission,Drive type,Fuel Type,Exterior Color,Interior Color,Accidents,Owners,Car Usage Type,Location,Price
VIN,,,,,,,,,,,,,,,,,,
1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"
3N1AB7AP7HY219190,Nissan,Sentra,S CVT,2017,"140,062 miles",29,37,1.8L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,2 Owners,Personal use,"Bourbonnais, IL","$8,900"
1FT7W2A67NEC61857,Ford,Super,XL Crew Cab 8' Box 2WD,2022,"32,089 miles",6.2L V,8 Gas,Automatic,NaN,RWD,Automatic,White,Gray,No accidents,1 Owner,Personal use,"Odessa, TX","$48,987"
WDDXJ8FB6GA015695,Mercedes-Benz,S-Class,S 550 4MATIC Coupe,2016,"17,034 miles",16,24,4.6L V-8 Gas Turbocharged,Automatic,AWD,Gas,Gray,Red,No accidents,2 Owners,Personal use,"Duluth, GA","$72,988"
5N1AT2MV4JC726551,Nissan,Rogue,SV AWD,2018,"51,138 miles",25,32,2.5L Inline-4 Gas,Automatic,AWD,Gas,Blue,Black,No accidents,2 Owners,Fleet use,"Manassas, VA","$20,995"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1FTFW1EF4EFB51083,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2014,"99,989 miles",14,19,5.0L V-8 Gas,Automatic,4WD,Gas,White,Black,No accidents,1 Owner,Personal use,"Van Nuys, CA","$20,988"
1FT7W2BT5KEF00323,Ford,Super,Lariat 4WD Crew Cab 6.75' Box,2019,"29,594 miles",6.7L V,8 Diesel Turbocharged,Automatic,NaN,4WD,Automatic,Gray,Black,No accidents,1 Owner,Personal use,"Waco, TX","$67,995"
1N4BL4BV0LC207822,Nissan,Altima,2.5 S FWD,2020,"62,595 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,Gray,Black,1 accident,1 Owner,Personal use,"Ocala, FL","$19,792"
2C4RDGBG7KR591208,Dodge,Grand,SE,2019,"124,972 miles",17,25,3.6L V-6 Gas,Automatic,FWD,Gas,Silver,Black,No accidents,2 Owners,Fleet use,"Wenatchee, WA","$16,995"
WBXHT3C35J5K31260,BMW,X1,xDrive28i AWD,2018,"60,601 miles",22,31,2.0L Inline-4 Gas Turbocharged,Automatic,AWD,Gas,White,Beige,1 accident,2 Owners,Personal use,"Reno, NV","$26,999"

### Final Dataset after dropping the null values

In [32]:
df=df.dropna()
df=df.reset_index()

In [33]:
df

,VIN,Brand,Model,Trim,Manufature Year,Mileage,MPG City,MPG Highway,Engine,Transmission,Drive type,Fuel Type,Exterior Color,Interior Color,Accidents,Owners,Car Usage Type,Location,Price
0,1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"
1,3N1AB7AP7HY219190,Nissan,Sentra,S CVT,2017,"140,062 miles",29,37,1.8L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,2 Owners,Personal use,"Bourbonnais, IL","$8,900"
2,WDDXJ8FB6GA015695,Mercedes-Benz,S-Class,S 550 4MATIC Coupe,2016,"17,034 miles",16,24,4.6L V-8 Gas Turbocharged,Automatic,AWD,Gas,Gray,Red,No accidents,2 Owners,Personal use,"Duluth, GA","$72,988"
3,5N1AT2MV4JC726551,Nissan,Rogue,SV AWD,2018,"51,138 miles",25,32,2.5L Inline-4 Gas,Automatic,AWD,Gas,Blue,Black,No accidents,2 Owners,Fleet use,"Manassas, VA","$20,995"
4,4T1G11AK3LU926676,Toyota,Camry,SE FWD Automatic,2020,"62,598 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,1 Owner,Personal use,"Cornelius, NC","$25,599"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13720,1ZVFT80NX55102814,Ford,Mustang,2dr Coupe Premium,2005,"174,987 miles",19,28,4.0L V-6 Gas,Automatic,RWD,Gas,Silver,Black,1 accident,5 Owners,Personal use,"Austin, TX","$6,499"
13721,1FTFW1EF4EFB51083,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2014,"99,989 miles",14,19,5.0L V-8 Gas,Automatic,4WD,Gas,White,Black,No accidents,1 Owner,Personal use,"Van Nuys, CA","$20,988"
13722,1N4BL4BV0LC207822,Nissan,Altima,2.5 S FWD,2020,"62,595 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,Gray,Black,1 accident,1 Owner,Personal use,"Ocala, FL","$19,792"
13723,2C4RDGBG7KR591208,Dodge,Grand,SE,2019,"124,972 miles",17,25,3.6L V-6 Gas,Automatic,FWD,Gas,Silver,Black,No accidents,2 Owners,Fleet use,"Wenatchee, WA","$16,995"
13724,WBXHT3C35J5K31260,BMW,X1,xDrive28i AWD,2018,"60,601 miles",22,31,2.0L Inline-4 Gas Turbocharged,Automatic,AWD,Gas,White,Beige,1 accident,2 Owners,Personal use,"Reno, NV","$26,999"

In [34]:
new_dataset=df[:201]
new_dataset

,VIN,Brand,Model,Trim,Manufature Year,Mileage,MPG City,MPG Highway,Engine,Transmission,Drive type,Fuel Type,Exterior Color,Interior Color,Accidents,Owners,Car Usage Type,Location,Price
0,1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"
1,3N1AB7AP7HY219190,Nissan,Sentra,S CVT,2017,"140,062 miles",29,37,1.8L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,2 Owners,Personal use,"Bourbonnais, IL","$8,900"
2,WDDXJ8FB6GA015695,Mercedes-Benz,S-Class,S 550 4MATIC Coupe,2016,"17,034 miles",16,24,4.6L V-8 Gas Turbocharged,Automatic,AWD,Gas,Gray,Red,No accidents,2 Owners,Personal use,"Duluth, GA","$72,988"
3,5N1AT2MV4JC726551,Nissan,Rogue,SV AWD,2018,"51,138 miles",25,32,2.5L Inline-4 Gas,Automatic,AWD,Gas,Blue,Black,No accidents,2 Owners,Fleet use,"Manassas, VA","$20,995"
4,4T1G11AK3LU926676,Toyota,Camry,SE FWD Automatic,2020,"62,598 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,1 Owner,Personal use,"Cornelius, NC","$25,599"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,1FTFW1EF4EFB51083,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2014,"99,989 miles",14,19,5.0L V-8 Gas,Automatic,4WD,Gas,White,Black,No accidents,1 Owner,Personal use,"Van Nuys, CA","$20,988"
197,1N4BL4BV0LC207822,Nissan,Altima,2.5 S FWD,2020,"62,595 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,Gray,Black,1 accident,1 Owner,Personal use,"Ocala, FL","$19,792"
198,2C4RDGBG7KR591208,Dodge,Grand,SE,2019,"124,972 miles",17,25,3.6L V-6 Gas,Automatic,FWD,Gas,Silver,Black,No accidents,2 Owners,Fleet use,"Wenatchee, WA","$16,995"
199,WBXHT3C35J5K31260,BMW,X1,xDrive28i AWD,2018,"60,601 miles",22,31,2.0L Inline-4 Gas Turbocharged,Automatic,AWD,Gas,White,Beige,1 accident,2 Owners,Personal use,"Reno, NV","$26,999"
200,1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"

In [35]:
file = 'TrueCar Used Cars Dataset'
new_dataset.to_csv("{}.csv".format(file))

In [36]:
final_dataset = pd.read_csv('TrueCar Used Cars Dataset.csv',index_col=0)

In [37]:
final_dataset

,VIN,Brand,Model,Trim,Manufature Year,Mileage,MPG City,MPG Highway,Engine,Transmission,Drive type,Fuel Type,Exterior Color,Interior Color,Accidents,Owners,Car Usage Type,Location,Price
0,1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"
1,3N1AB7AP7HY219190,Nissan,Sentra,S CVT,2017,"140,062 miles",29,37,1.8L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,2 Owners,Personal use,"Bourbonnais, IL","$8,900"
2,WDDXJ8FB6GA015695,Mercedes-Benz,S-Class,S 550 4MATIC Coupe,2016,"17,034 miles",16,24,4.6L V-8 Gas Turbocharged,Automatic,AWD,Gas,Gray,Red,No accidents,2 Owners,Personal use,"Duluth, GA","$72,988"
3,5N1AT2MV4JC726551,Nissan,Rogue,SV AWD,2018,"51,138 miles",25,32,2.5L Inline-4 Gas,Automatic,AWD,Gas,Blue,Black,No accidents,2 Owners,Fleet use,"Manassas, VA","$20,995"
4,4T1G11AK3LU926676,Toyota,Camry,SE FWD Automatic,2020,"62,598 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,White,Black,1 accident,1 Owner,Personal use,"Cornelius, NC","$25,599"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,1FTFW1EF4EFB51083,Ford,F-150,XLT SuperCrew 5.5' Box 4WD,2014,"99,989 miles",14,19,5.0L V-8 Gas,Automatic,4WD,Gas,White,Black,No accidents,1 Owner,Personal use,"Van Nuys, CA","$20,988"
197,1N4BL4BV0LC207822,Nissan,Altima,2.5 S FWD,2020,"62,595 miles",28,39,2.5L Inline-4 Gas,Automatic,FWD,Gas,Gray,Black,1 accident,1 Owner,Personal use,"Ocala, FL","$19,792"
198,2C4RDGBG7KR591208,Dodge,Grand,SE,2019,"124,972 miles",17,25,3.6L V-6 Gas,Automatic,FWD,Gas,Silver,Black,No accidents,2 Owners,Fleet use,"Wenatchee, WA","$16,995"
199,WBXHT3C35J5K31260,BMW,X1,xDrive28i AWD,2018,"60,601 miles",22,31,2.0L Inline-4 Gas Turbocharged,Automatic,AWD,Gas,White,Beige,1 accident,2 Owners,Personal use,"Reno, NV","$26,999"
200,1FTFW1CT8EFC74622,Ford,F-150,XLT SuperCrew 5.5' Box RWD,2014,"222,150 miles",17,23,3.5L V-6 Gas Turbocharged,Automatic,RWD,Gas,Red,Gray,No accidents,2 Owners,Personal use,"Pembroke Pines, FL","$12,995"